### ISSUE TITLE
Homepage scrolls horizontally in IE11

### ISSUE THREAD

**Issue by mxsnyder** [baltimorecounty/baltimorecountymd.gov-assets#28]
The homepage scrolls horizontally in IE11. I've narrowed it down to the search box being the issue, and the snippet below shows the change I made in the inspector that seemed to make the problem go away. 

```CSS
.carousel-wrapper .search-container {
    position: absolute;
    right: 50%; /* changed from left: -50% */
    z-index: 999;
    -moz-transform: translateX(-50%);
    -o-transform: translateX(-50%);
    -webkit-transform: translateX(-50%);
    transform: translateX(50%);
}
```
